### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by Heromyth** [vuejs/router#1373]
### Version
4.0.14

### Reproduction link
[github.com](https://github.com/hsiangleev/element-plus-admin/blob/master/src/store/modules/layout.ts#L159)

### Steps to reproduce
1. git clone https://github.com/hsiangleev/element-plus-admin.git
2. `cd element-plus-admin` and `code .`
3. open `src\store\modules\layout.ts`, jump to [line 159](https://github.com/hsiangleev/element-plus-admin/blob/master/src/store/modules/layout.ts#L159), and replace this line with `router.push('/login')`
4. `npm install` and `npm run dev`
5. open the server link and login
6. open two pages like `http://localhost:3002/#/ErrorPage/404` and `http://localhost:3002/#/ErrorPage/401`
7. click `logout` in the user's dropdown-menu

### What is expected?
Can go back to the login page using the logout button.

### What is actually happening?
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'nextSibling')
    at nextSibling (runtime-dom.esm-bundler.js:36:31)
    at getNextHostNode (runtime-core.esm-bundler.js:5632:16)
    at getNextHostNode (runtime-core.esm-bundler.js:5627:20)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5111:17)
    at ReactiveEffect.run (reactivity.esm-bundler.js:146:25)
    at Object.leavingHooks.afterLeave (runtime-core.esm-bundler.js:2012:34)
    at performRemove (runtime-core.esm-bundler.js:5547:28)
    at leave (runtime-core.esm-bundler.js:2129:24)
    at performLeave (runtime-core.esm-bundler.js:5554:40)
    at remove2 (runtime-core.esm-bundler.js:5559:17)
nextSibling @ runtime-dom.esm-bundler.js:36
getNextHostNode @ runtime-core.esm-bundler.js:5632
getNextHostNode @ runtime-core.esm-bundler.js:5627
componentUpdateFn @ runtime-core.esm-bundler.js:5111
run @ reactivity.esm-bundler.js:146
leavingHooks.afterLeave @ runtime-core.esm-bundler.js:2012
performRemove @ runtime-core.esm-bundler.js:5547
leave @ runtime-core.esm-bundler.js:2129
performLeave @ runtime-core.esm-bundler.js:5554
remove2 @ runtime-core.esm-bundler.js:5559
unmount @ runtime-core.esm-bundler.js:5521
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
patch @ runtime-core.esm-bundler.js:4458
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
updateComponent @ runtime-core.esm-bundler.js:4968
processComponent @ runtime-core.esm-bundler.js:4901
patch @ runtime-core.esm-bundler.js:4489
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:146
leavingHooks.afterLeave @ runtime-core.esm-bundler.js:2012
performRemove @ runtime-core.esm-bundler.js:5547
leave @ runtime-core.esm-bundler.js:2129
performLeave @ runtime-core.esm-bundler.js:5554
remove2 @ runtime-core.esm-bundler.js:5559
unmount @ runtime-core.esm-bundler.js:5521
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
unmount @ runtime-core.esm-bundler.js:2442
(匿名) @ runtime-core.esm-bundler.js:2494
(匿名) @ runtime-core.esm-bundler.js:2483
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2667
invokeArrayFns @ shared.esm-bundler.js:556
unmountComponent @ runtime-core.esm-bundler.js:5584
unmount @ runtime-core.esm-bundler.js:5494
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
unmountChildren @ runtime-core.esm-bundler.js:5622
unmount @ runtime-core.esm-bundler.js:5512
unmountChildren @ runtime-core.esm-bundler.js:5622
unmount @ runtime-core.esm-bundler.js:5512
unmountChildren @ runtime-core.esm-bundler.js:5622
unmount @ runtime-core.esm-bundler.js:5512
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
unmountChildren @ runtime-core.esm-bundler.js:5622
unmount @ runtime-core.esm-bundler.js:5512
unmountComponent @ runtime-core.esm-bundler.js:5593
unmount @ runtime-core.esm-bundler.js:5494
patch @ runtime-core.esm-bundler.js:4458
componentUpdateFn @ runtime-core.esm-bundler.js:5107
run @ reactivity.esm-bundler.js:167
callWithErrorHandling @ runtime-core.esm-bundler.js:155
flushJobs @ runtime-core.esm-bundler.js:394
Promise.then(异步)
nextTick @ runtime-core.esm-bundler.js:246
updateLabelWidth @ label-wrap.ts:42
(匿名) @ label-wrap.ts:60
callWithErrorHandling @ runtime-core.esm-bundler.js:155
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:164
Show 124 more frames
```

---
The `router-link` also has the same problem. For test:
```html
                    <el-dropdown-item>
                        <router-link :to='{ path: &apos;/login&apos; }'>logout</router-link>
                    </el-dropdown-item>
```

**Comment by posva** [comment]
Your reproduction is not minimal, please read and follow https://new-issue.vuejs.org/?repo=vuejs/vue-next#why-repro when reporting a bug. There should be no element plus in repro.

**Comment by Heromyth** [comment]
So sad

**Comment by lidaining-web** [comment]
我也遇到了这个问题, 不知所措

**Comment by sujiewen** [comment]
I also encountered this problem. If I shield keep-alive, it will not appear

**Comment by sujiewen** [comment]
Is there a solution?

**Comment by Cano1997** [comment]
我也遇到了

**Comment by Cano1997** [comment]
问题解决了，不要在keep-alive里面的component上加key

**Comment by geraldmuvengei06** [comment]
Same problem

**Comment by Foddie2** [comment]
Anyone with a solution to this
