### ISSUE TITLE
The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by V35CH** [vuejs/router#1463]
### Version
4.1.1

### Reproduction link
[github.com/V35CH/vue-gtm-test](https://github.com/V35CH/vue-gtm-test)

### Steps to reproduce
Try to build the application.

### What is expected?
Correct Build.

### What is actually happening?
Build Error is thrown:

✘ [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "vue-router". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "vue-router" package

    node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40945:10:
      40945 │     throw new Error(`Failed to resolve entry for package "${id}". ` +
            ╵           ^

    at packageEntryFailure (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40945:11)
    at resolvePackageEntry (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40941:9)
    at tryNodeResolve (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40748:20)
    at Context.resolveId (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40556:28)
    at Object.resolveId (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39229:55)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:61552:27
    at async node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38746:34
    at async callback (node_modules/esbuild/lib/main.js:921:28)
    at async handleRequest (node_modules/esbuild/lib/main.js:701:30)

  This error came from the "onResolve" callback registered here:

    node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38725:18:
      38725 │             build.onResolve({ filter: /^[\w@][^:]/ }, async ({ path: id, importer, kind }) => {
            ╵                   ~~~~~~~~~

    at setup (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:38725:19)
    at handlePlugins (node_modules/esbuild/lib/main.js:843:23)
    at Object.buildOrServe (node_modules/esbuild/lib/main.js:1137:7)
    at node_modules/esbuild/lib/main.js:2085:17
    at new Promise (<anonymous>)
    at Object.build (node_modules/esbuild/lib/main.js:2084:14)
    at Object.build (node_modules/esbuild/lib/main.js:1931:51)
    at runOptimizeDeps (node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:39969:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

  The plugin "vite:dep-pre-bundle" was triggered by this import

    node_modules/@gtm-support/vue-gtm/dist/index.js:66:69:
      66 │         vueRouterModule = await Promise.resolve().then(() => require('vue-router'));
         ╵                                                                      ~~~~~~~~~~~~

9:36:49 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/vite/dist/node/chunks/dep-80fe9c6b.js:40945:10: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "vue-router". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "vue-router" package
    at failureErrorWithLog (node_modules/esbuild/lib/main.js:1605:15)
    at node_modules/esbuild/lib/main.js:1251:28
    at runOnEndCallbacks (node_modules/esbuild/lib/main.js:1034:63)
    at buildResponseToResult (node_modules/esbuild/lib/main.js:1249:7)
    at node_modules/esbuild/lib/main.js:1358:14
    at node_modules/esbuild/lib/main.js:666:9
    at handleIncomingPacket (node_modules/esbuild/lib/main.js:763:9)
    at Socket.readFromStdout (node_modules/esbuild/lib/main.js:632:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)

---
also see here: https://github.com/gtm-support/vue-gtm/issues/226
With vue-router 4.0.16 no errors occur.

**Comment by posva** [comment]
Please open an issue without external libraries like Vue gtm so I can check

**Comment by Shinigami92** [comment]
@posva you should really look into the reproduction provided here, because vue-router 4.0 was working in my plugin just fine
But now even users that do not use vue-router as a dependency get errors based on this issue
And a version change from v4.0 to v4.1 is not a breaking change in terms of semver
Please work on a solution to make it backward compatible again with 4.x or revert and release a 5.0 for the new breaking change

**Comment by simonfunk** [comment]
Not a nice way always close issue and request to open new one when user already provide a good example 🖓

**Comment by posva** [comment]
Having no external dependencies is well mentioned in the issue reporting guidelines. This is not a “good” reproduction. It’s standard for this to get closed…
In any case, I’m already looking into the issue but I welcome a proper reproduction in a new issue
