### ISSUE TITLE
[SSR]Error when switching routes

### ISSUE THREAD

**Issue by see** [vuejs/router#1485]
### Version
4.1.2

### Reproduction link
[github.com/see/vite-ssr-issue](https://github.com/see/vite-ssr-issue)

### Steps to reproduce
1. yarn install
2. yarn build
3. node server.prod.cjs
4. vist http://localhost:3000/mobile/

### What is expected?
It works when switching routes

### What is actually happening?

see vitejs/vite#9335

```
index.7a815253.js:1 TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (index.7a815253.js:1:51645)
    at X (index.7a815253.js:1:37703)
    at Q (index.7a815253.js:1:37098)
    at O (index.7a815253.js:1:36528)
    at vs.C [as fn] (index.7a815253.js:1:40799)
    at vs.run (index.7a815253.js:1:4604)
    at u.update (index.7a815253.js:1:41070)
    at ue (index.7a815253.js:1:41096)
    at Ce (index.7a815253.js:1:39923)
    at N (index.7a815253.js:1:39716)
```

```
index.7a815253.js:1 TypeError: Cannot read properties of null (reading 'parentNode')
    at parentNode (index.7a815253.js:1:52062)
    at vs.C [as fn] (index.7a815253.js:1:40376)
    at vs.run (index.7a815253.js:1:4604)
    at u.update (index.7a815253.js:1:41070)
    at lt (index.7a815253.js:1:12478)
    at no (index.7a815253.js:1:14177)
```

**Comment by posva** [comment]
This seems unrelated to the router, the error happens without the router as well: you have a Hydration mismatch. It shows properly in dev:

![Screenshot 2022-07-24 at 17 46 23](https://user-images.githubusercontent.com/664177/180655253-216ff644-8bee-4392-a195-c1e6ba864dd2.png)

After removing all the extra dependencies (eslint, cypress, extra vite plugins) I can't see the error you mention. Let me know if you manage to reproduce without the extra vite plugins.

**Comment by see** [comment]
It works in version 4.0.16

**Comment by see** [comment]
@posva I remove all the extra dependencies (eslint, cypress, extra vite plugins), It still does not work.

**Comment by see** [comment]
@posva Changing this line to `router.push(url.replace(/^\/mobile\//, ''));` will remove the hydration mismatch error.
https://github.com/see/vite-ssr-issue/blob/7e8ad9fae463b88542cdaa411b47ae482b4c751f/src/entry-server.ts#L13

**Comment by posva** [comment]
> Let me know if you manage to reproduce without the extra vite plugins.

Thanks
