### ISSUE TITLE
vue-router not working properly when overriding Set's Symbol.iterator

### ISSUE THREAD

**Issue by a1518079148** [vuejs/router#1664]
### Version
4.1.6

### Reproduction link
[jsfiddle.net/rwujqztf/3/](https://jsfiddle.net/rwujqztf/3/)

### Steps to reproduce
see https://jsfiddle.net/rwujqztf/3/

### What is expected?
run

### What is actually happening?
[Vue Router warn]: Unexpected error when starting the router: TypeError: effect2.run is not a function
    at triggerEffect (reactivity.esm-bundler.js:400:20)
    at triggerEffects (reactivity.esm-bundler.js:387:13)
    at triggerRefValue (reactivity.esm-bundler.js:1003:13)
    at set value [as value] (reactivity.esm-bundler.js:1048:13)
    at finalizeNavigation (vue-router.mjs:3334:22)
    at vue-router.mjs:3207:27

**Comment by posva** [comment]
If you override the native Set iterator, you should ensure it keeps the same behavior and properties as the existing one to avoid breaking any lib using Set, not just Vue Router. Moving to a discussion as a question as this is not directly related to vue router
