### ISSUE TITLE
Add Bun support

### ISSUE THREAD

**Issue by danulqua** [vuejs/router#1982]
### What problem is this solving

[Bun](https://bun.sh/) has been released - fast, all-in-one toolkit for running, building, testing, and debugging JavaScript and TypeScript, from a single file to a full-stack application.

I believe that it opens up a door to the future of JavaScript tooling, but in order to become great, developers of platforms, frameworks, libraries, etc. are grouping up to support Bun, because there are currently numerous existing problems that need to be solved.

### Proposed solution

I have an existing Vue 3 project which I created using:

```sh
npm create vue@latest
```

App also uses Vue Router.

In `package.json` I modified the `dev` script to this:

```json
"dev": "bun --hot src/main.ts",
```

When trying to run the application, I get this error:

```sh
$ bun --hot src/main.ts
[0.05ms] ".env.development.local"
482 |         position: window.history.length,
483 |         scroll: computeScroll ? computeScrollPosition() : null,
484 |     };
485 | }
486 | function useHistoryStateNavigation(base) {
487 |     const { history, location } = window;
                                      ^
ReferenceError: Can't find variable: window
      at useHistoryStateNavigation (/Users/danil0110/dev/dedeshevshe/dedeshevshe-frontend-bun/node_modules/vue-router/dist/vue-router.mjs:487:34)
      at createWebHistory (/Users/danil0110/dev/dedeshevshe/dedeshevshe-frontend-bun/node_modules/vue-router/dist/vue-router.mjs:582:30)
      at /Users/danil0110/dev/dedeshevshe/dedeshevshe-frontend-bun/src/router/index.ts:9:11
482 |         position: window.history.length,
483 |         scroll: computeScroll ? computeScrollPosition() : null,
484 |     };
485 | }
486 | function useHistoryStateNavigation(base) {
487 |     const { history, location } = window;
                                      ^
ReferenceError: Can't find variable: window
      at useHistoryStateNavigation (/Users/danil0110/dev/dedeshevshe/dedeshevshe-frontend-bun/node_modules/vue-router/dist/vue-router.mjs:487:34)
      at createWebHistory (/Users/danil0110/dev/dedeshevshe/dedeshevshe-frontend-bun/node_modules/vue-router/dist/vue-router.mjs:582:30)
      at /Users/danil0110/dev/dedeshevshe/dedeshevshe-frontend-bun/src/router/index.ts:9:11
```

**Comment by posva** [comment]
Check https://router.vuejs.org/guide/essentials/history-mode.html#Different-History-modes
Same as with node, you need to use a different history mode
