### ISSUE TITLE
vue3 路径跳转问题

### ISSUE THREAD

**Issue by longshiyin** [vuejs/router#2428]
### Reproduction

https://qa-ga.helipay.com/ncbmerchant/crossBorder/batchRemittance/index

### Steps to reproduce the bug

点击跨境汇款里面的批量跨境汇款菜单后点击页面的发起跨境汇款按钮，然后再点击批量跨境汇款菜单控制台就会提示错误，并且跳转也是不成功，点击其他的菜单也是控制台提示错误不能进行跳转

### Expected behavior

点击跨境汇款里面的批量跨境汇款菜单后点击页面的发起跨境汇款按钮，再从发起跨境汇款页面之间点击批量跨境汇款菜单能够跳转到页面

### Actual behavior

点击跨境汇款里面的批量跨境汇款菜单后点击页面的发起跨境汇款按钮，再从发起跨境汇款页面之间点击批量跨境汇款菜单跳转失败

**Comment by longshiyin** [comment]
控制台提示：index.ce365e55.js:3 [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <ElIcon key=0 onClick=fn > 
  at <Item ref_for=true ref="tagsViewItem" key="message.menu.crossBorder.batchRemittance"  ... > 
  at <ElScrollbar class="scroll-container tags-view-container" ref="scrollbarDom" onWheelPassive=fn<x>  ... > 
  at <Index> 
  at <ElContainer> 
  at <ElContainer style= Object > 
  at <Index onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) > > 
  at <RouterView> 
  at <ElConfigProvider locale= Object size="default" > 
  at <App>
  console打印：Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at insert (index.ce365e55.js:14:10557)
    at k (index.ce365e55.js:13:2380)
    at C (index.ce365e55.js:13:1625)
    at g (index.ce365e55.js:13:805)
    at Ec.Ae [as fn] (index.ce365e55.js:13:6286)
    at Ec.run (index.ce365e55.js:1:7841)
    at V.q.update (index.ce365e55.js:13:6594)
    at V (index.ce365e55.js:13:6724)
    at N (index.ce365e55.js:13:5130)
    at H (index.ce365e55.js:13:4830)
